### ISSUE TITLE
"If this doesn't work, please report the error here:" message

### ISSUE THREAD

**Issue by nekromoff** [keredson/gnomecast#121]
~$ pip3 install gnomecast   
Collecting gnomecast
  Using cached https://files.pythonhosted.org/packages/7c/d9/d32746c06b75b0a80505bb6fbbed5ca22aa00ace5534726b3b06f4b23262/gnomecast-1.9.7.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: No module named 'pychromecast'
    No module named '_dbus_bindings'

**Comment by dsg38** [comment]
Very similar (Ubuntu 20.04):
```
No module named 'pychromecast'
No module named 'dbus'
```

Suggests installing `python3-gi` but it's already installed

**Comment by nekromoff** [comment]
Yes, it installed for me as well.

**Comment by dsg38** [comment]
I was actually using my conda install of pip (still python 3) - just retried with pip3 (ubuntu base) and it did install but still not showing up in my path or the launcher

**Comment by keredson** [comment]
@dsg38 can you run it w/ `python3 -m gnomecast`?

and do you have a `~/.local/share/applications/gnomecast.desktop`?

**Comment by SanderBorra** [comment]
sander@lappie:~/.local/bin$ ./gnomecast 
Traceback (most recent call last):
  File "./gnomecast", line 8, in <module>
    sys.exit(main())
  File "/home/sander/.local/lib/python3.8/site-packages/gnomecast.py", line 1567, in main
    caster = Gnomecast()
  File "/home/sander/.local/lib/python3.8/site-packages/gnomecast.py", line 396, in __init__
    self.ip = (([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + [None])[0]
socket.gaierror: [Errno -2] Name or service not known
sander@lappie:~/.local/bin$  python3 -m gnomecast
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sander/.local/lib/python3.8/site-packages/gnomecast.py", line 1571, in <module>
    main()
  File "/home/sander/.local/lib/python3.8/site-packages/gnomecast.py", line 1567, in main
    caster = Gnomecast()
  File "/home/sander/.local/lib/python3.8/site-packages/gnomecast.py", line 396, in __init__
    self.ip = (([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + [None])[0]
socket.gaierror: [Errno -2] Name or service not known
