### ISSUE TITLE
Fedora 33 - error starting gnomecast

### ISSUE THREAD

**Issue by didierga** [keredson/gnomecast#150]
Hi,
I use Fedora 33 and I get following error starting gnomecast.
I tried to uninstall/reinstall gnomecast with no sucess.
Thanks for your help.

```
$ gnomecast
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (gnomecast 1.9.11 (/home/didier/.local/lib/python3.9/site-packages), Requirement.parse('gnomecast==1.9.7'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gnomecast", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gnomecast==1.9.7' distribution was not found and is required by the application

```

**Comment by didierga** [comment]
`$ gnomecast` does not work but
`$ python3 -m gnomecast` works fine.
It is possible after installation to edit the launcher with alacarte program.
