### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by TheOncomingStorm** [keredson/gnomecast#170]
The first time I run gnomecast I get a slightly different error of "socket.herror" but then it goes with the one below afterward. 

`Traceback (most recent call last):
  File "/usr/bin/gnomecast", line 33, in <module>
    sys.exit(load_entry_point('gnomecast==1.9.11', 'gui_scripts', 'gnomecast')())
  File "/usr/lib/python3.9/site-packages/gnomecast.py", line 1570, in main
    caster = Gnomecast()
  File "/usr/lib/python3.9/site-packages/gnomecast.py", line 396, in __init__
    self.ip = (([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + [None])[0]
socket.gaierror: [Errno -2] Name or service not known
`

**Comment by TheOncomingStorm** [comment]
I just ran the test_gnomecast.py and I got the following. Something I find interesting is the "E" after "AttributeError: 'Transcoder' object has no attribute 'p'". AFAIK, this wasn't an accidental keypress. I'm sure it doesn't matter but figured I'd point it out just in case.  Note, I removed full path info to keep from revealing any personal info..


`Exception ignored in: <function Transcoder.__del__ at 0x7f7b81739160>
Traceback (most recent call last):
  File "gnomecast-git/src/gnomecast/gnomecast.py", line 390, in __del__
    self.destroy()
  File "gnomecast-git/src/gnomecast/gnomecast.py", line 384, in destroy
    if self.p and self.p.poll() is None:
AttributeError: 'Transcoder' object has no attribute 'p'
E
Stream #0:3(eng): Subtitle: dvd_subtitle, 1920x1080 0:3(eng)
Stream #0:4(ara): Subtitle: dvd_subtitle, 1920x1080 0:4(ara)
Stream #0:5(chi): Subtitle: dvd_subtitle, 1920x1080 0:5(chi)
Stream #0:6(fre): Subtitle: dvd_subtitle, 1920x1080 0:6(fre)
Stream #0:7(kor): Subtitle: dvd_subtitle, 1920x1080 0:7(kor)
Stream #0:8(spa): Subtitle: dvd_subtitle, 1920x1080 0:8(spa)
FileMetadata(fn:Godzilla - King of the Monsters (2019) (2160p BluRay x265 10bit HDR Tigole).mkv, ready:True, thumbnail_fn:None, container:mkv, video_streams:[StreamMetadata(index:0:0, codec:hevc, title:Video #1)], audio_streams:[AudioMetadata(index:0:1, codec:aac, title:eng, channels:8), AudioMetadata(index:0:2, codec:aac, title:Commentary, channels:2)], subtitles:[StreamMetadata(index:0:3, title:eng), StreamMetadata(index:0:4, title:ara), StreamMetadata(index:0:5, title:chi), StreamMetadata(index:0:6, title:fre), StreamMetadata(index:0:7, title:kor), StreamMetadata(index:0:8, title:spa)])
Exception ignored in: <function Transcoder.__del__ at 0x7f7b81739160>
Traceback (most recent call last):
  File "gnomecast-git/src/gnomecast/gnomecast.py", line 390, in __del__
    self.destroy()
  File "gnomecast-git/src/gnomecast/gnomecast.py", line 384, in destroy
    if self.p and self.p.poll() is None:
AttributeError: 'Transcoder' object has no attribute 'p'
E
======================================================================
ERROR: test_1 (__main__.TestGnomecast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gnomecast-git/src/gnomecast/test_gnomecast.py", line 62, in test_1
    transcoder = gnomecast.Transcoder(cast, fmd, fmd.video_streams[0], fmd.audio_streams[0], None, fake=True)
TypeError: __init__() missing 1 required positional argument: 'error_callback'

======================================================================
ERROR: test_2 (__main__.TestGnomecast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gnomecast-git/src/gnomecast/test_gnomecast.py", line 219, in test_2
    transcoder = gnomecast.Transcoder(cast, fmd, fmd.video_streams[0], fmd.audio_streams[0], None, fake=True)
TypeError: __init__() missing 1 required positional argument: 'error_callback'

----------------------------------------------------------------------
Ran 2 tests in 2.006s

FAILED (errors=2)
`
