### ISSUE TITLE
Codec issue when playing video

### ISSUE THREAD

**Issue by paci4416** [keredson/gnomecast#31]
Hey,
I'm trying to cast a video to my chromecast and I get this error when hitting play:

Exception happened during processing of request from ('192.168.1.18', 39594)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/dist-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/usr/local/lib/python3.5/dist-packages/paste/httpserver.py", line 307, in wsgi_execute
    self.wsgi_write_chunk(chunk)
  File "/usr/local/lib/python3.5/dist-packages/paste/httpserver.py", line 161, in wsgi_write_chunk
    self.send_header(k, v)
  File "/usr/lib/python3.5/http/server.py", line 512, in send_header
    ("%s: %s\r\n" % (keyword, value)).encode('latin-1', 'strict'))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u05d4' in position 15: ordinal not in range(256)

This is the information I see when loading my video:
file.mkv mkv h264 True True False True
['ffmpeg', '-i', '/media/yehuda/folder/file.mkv', '-c:v', 'copy', '-c:a', 'mp3', '/tmp/movie_caster_p81pwax9.mp4']

Thanks.

**Comment by keredson** [comment]
could you run this for me and copy the output here?
```
ffmpeg -i /media/yehuda/folder/file.mkv -f ffmetadata -
```

**Comment by paci4416** [comment]
~> ffmpeg -i file.mkv -f ffmetadata -
ffmpeg version 3.3.3-2~ubuntu16.04.1~ppa1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version='2~ubuntu16.04.1~ppa1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, matroska,webm, from 'file.mkv':
  Metadata:
    encoder         : libebml v1.3.0 + libmatroska v1.4.1
    creation_time   : 2014-03-10T02:18:38.000000Z
  Duration: 00:43:47.34, start: 0.000000, bitrate: 4212 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc
    Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
;FFMETADATA1
Output #0, ffmetadata, to 'pipe:':
  Metadata:
    encoder         : Lavf57.71.100
Stream mapping:
Press [q] to stop, [?] for help
encoder=Lavf57.71.100
size=       0kB time=-577014:32:22.77 bitrate=N/A speed=N/A    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded

**Comment by keredson** [comment]
Does this happen with all files or just this one?

**Comment by paci4416** [comment]
Just tried a few more and I get the same error.

The only difference is the character in the error.
the character '\u05d4' is a character in Hebrew that represents Thursday.
and the error I get now is with the character '\u05e9' which represents Saturday in Hebrew.

**Comment by keredson** [comment]
that helps a lot, thanks.  i suspect it's where bottle is setting the 'Last-Modified' header.  ('Thu, 05 Dec 2013 18:43:53 GMT' for an example.)  likely a regional encoding feature.  see here: https://github.com/bottlepy/bottle/blob/master/bottle.py#L2891

i can unset that header.  i can't image the chromecast is dependent on it.

**Comment by keredson** [comment]
can you test https://github.com/keredson/gnomecast/pull/33 and see if it fixes?

**Comment by paci4416** [comment]
#33  Fixed the issue
Thank you.
