### ISSUE TITLE
No dbus name found exceptions

### ISSUE THREAD

**Issue by OverkillGuy** [keredson/gnomecast#36]
Attempting to run gnomecast on Linux Mint using MATE desktop gives me the following:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.ScreenSaver': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gnomecast", line 9, in <module>
    load_entry_point('gnomecast==0.2.15', 'gui_scripts', 'gnomecast')()
  File "/usr/local/lib/python3.4/dist-packages/gnomecast.py", line 820, in main
    caster = Gnomecast()
  File "/usr/local/lib/python3.4/dist-packages/gnomecast.py", line 185, in __init__
    saver = bus.get_object('org.freedesktop.ScreenSaver', '/ScreenSaver')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_vname)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
 
```
Seems non-standard Screensaver bus location (it's hit me before on this laptop) causes an exception that is not handled.

## Investigation
I'll dig into the the issue on my side of why I have no such dbus name available. That seems legitimately important for other people in my unfortunate case to try to get the correct name.
The uncaught exception is for sure an immediate issue, and I'll prepare a PR soon, but I need to understand what kind of fallback mechanism is expected if we legit can't find any Screensaver handle.

**Comment by OverkillGuy** [comment]
All right, was able to locally work around the issue by using the "org.mate.freedesktop" value:

``` 
>>> import dbus
>>> bus = dbus.SessionBus()
>>> bus.get_object('org.mate.ScreenSaver', '/ScreenSaver')
<ProxyObject wrapping <dbus._dbus.SessionBus (session) at 0x7feeddfa6d00> :1.23 /ScreenSaver at 0x7feeeb1c2668>
>>> bus.get_object('org.freedesktop.ScreenSaver', '/ScreenSaver')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.ScreenSaver': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
```
I'll check if there are more common values for this parameter, and prepare a PR wrapping the get_object call like this:

```
    bus = dbus.SessionBus()
    self.saver_interface = find_screensaver_dbus_iface(bus)
```
