### ISSUE TITLE
The 'paste' distribution was not found and is required by gnomecast

### ISSUE THREAD

**Issue by boredland** [keredson/gnomecast#45]
```
Traceback (most recent call last):
  File "/usr/bin/gnomecast", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'paste' distribution was not found and is required by gnomecast
```

**Comment by keredson** [comment]
must have missed a dep.  thanks for the report.  if you run this you should be GTG: `sudo pip3 install paste`

**Comment by keredson** [comment]
hmm, no, seems i do have it in the deps:
```
  install_requires=['pychromecast','bottle','pycaption','paste'],
```
not sure what's going on here.

**Comment by boredland** [comment]
Thats strange, shouldn't `python setup.py install` get those dependencies?

**Comment by arulrajnet** [comment]
Same for me. This is the steps to follow

    virtualenv --system-site-packages -p python3 .venv
    source .venv/bin/activate
    pip3 install -r requirements.txt
    pip3 install paste
    python3 gnomecast.py

**Comment by fiendish** [comment]
Why do you install it in a virtualenv?

**Comment by arulrajnet** [comment]
@fiendish nothing fancy. I just don't want to mesh with my existing python packages which installed in system / user level. Virtualenv gives me isolated environmental for clean testing.

**Comment by fiendish** [comment]
Ah, for testing makes sense. I thought you meant just for using it. My bad.
:D

>

**Comment by keredson** [comment]
i see now `requirements.txt` was missing `paste`.  added.  thanks for the catch!
