### ISSUE TITLE
Attempting to install throws error

### ISSUE THREAD

**Issue by RyanNerd** [keredson/gnomecast#46]
Linux Mint 18.2
Kernel v4.15.7
HP Envy 4 core x64

`sudo pip3 install gnomecast`

```
The directory '/home/ryan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ryan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gnomecast
  Downloading https://files.pythonhosted.org/packages/51/d5/af6a82f39e7ecc9bf3d257511b1a67a190d6b15b31546719337f1d74a97b/gnomecast-0.2.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zAjlXO/gnomecast/setup.py", line 16, in <module>
        version=__import__('gnomecast').__version__,
      File "gnomecast.py", line 57
        nonlocal timer, lastest_args, latest_kwargs
                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zAjlXO/gnomecast/
```

**Comment by RyanNerd** [comment]
My internet was up and down like a yo-yo and I think this was causing the issues.
Got it installed. Thankx.

**Comment by keredson** [comment]
:+1: and thanks for the upvote on stackoverflow!
