### ISSUE TITLE
Error updating gnomecast in Fedora 29

### ISSUE THREAD

**Issue by didierga** [keredson/gnomecast#75]
Running Fedora 29 up to date and trying to update gnomecast from 1.4.1, I get following error:

*************************************
$ pip install update gnomecast
Collecting update
  Downloading https://files.pythonhosted.org/packages/9f/c4/dfe8a392edd35cc635c35cd3b20df6a746aacdeb39b685d1668b56bf819b/update-0.0.1-py2.py3-none-any.whl
Collecting gnomecast
  Downloading https://files.pythonhosted.org/packages/80/ec/8847970e97944647754e7790f29b1a7dc85b13f04f23513e1d735444219f/gnomecast-1.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qBMD04/gnomecast/setup.py", line 16, in <module>
        version=__import__('gnomecast').__version__,
      File "gnomecast.py", line 72
        nonlocal timer, lastest_args, latest_kwargs
                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qBMD04/gnomecast/
*************************************
Other problem trying to uninstall 1.4.1:
*************************************
$ whereis gnomecast
gnomecast: /usr/local/bin/gnomecast
$ gnomecast
No subtitles. -1 None
None
serving on http://192.168.1.10:51521
check_ffmpeg
b'/usr/bin/ffmpeg\n'
$ pip uninstall gnomecast
Skipping gnomecast as it is not installed.
*************************************
I am not a python expert and I will appreciate any help.

**Comment by keredson** [comment]
Is `python` Python 3 on Fedora?

**Comment by keredson** [comment]
If not try `pip3` instead of `pip`.

**Comment by keredson** [comment]
NP!
