### ISSUE TITLE
OpenSUSE Leap 15.0:  unable to start gnomecast 

### ISSUE THREAD

**Issue by ksafford** [keredson/gnomecast#78]
I installed gnomecast with 

`sudo pip3 install gnomecast` 

When I attempt to run:

> ╰─$ gnomecast
> Traceback (most recent call last):
>   File "/usr/bin/gnomecast", line 11, in <module>
>     load_entry_point('gnomecast==1.5.0', 'gui_scripts', 'gnomecast')()
>   File "/usr/lib/python3.6/site-packages/gnomecast.py", line 1200, in main
>     caster = Gnomecast()
>   File "/usr/lib/python3.6/site-packages/gnomecast.py", line 209, in __init__
>     self.ip = (([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + [None])[0]
> socket.gaierror: [Errno -2] Name or service not known

**Comment by ksafford** [comment]
Thanks for the response. The error doesn't seem to be happening anymore. I suspect it may have been related to my VPN.
