### ISSUE TITLE
ModuleNotFoundError: No module named 'transcode'

### ISSUE THREAD

**Issue by Naguz** [keredson/gnomecast#96]
I get an error message on launching gnomecast:

`Traceback (most recent call last):
  File "/usr/bin/gnomecast", line 11, in <module>
    load_entry_point('gnomecast==1.7.1', 'gui_scripts', 'gnomecast')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/gnomecast.py", line 13, in <module>
    from transcode import Transcoder, parse_ffmpeg_time, AUDIO_EXTS
ModuleNotFoundError: No module named 'transcode'
`
I can't seem to find what package provides the transcode module. Pip claims all dependencies for gnomecast are in order.

**Comment by banzr** [comment]
If you copy the transcode.py file located at the root of this repo to your python site-packages or possibly dist-packages folder, it will work.

**Comment by hopeseekr** [comment]
That worked for me, on Arch Linux. Thank you very much!

**Comment by banzr** [comment]
Glad to help!

**Comment by keredson** [comment]
fixed.  :)
